### ISSUE TITLE
v0.5.0: output lines in csv?

### ISSUE THREAD

**Issue by JayBrown** [derhuerst/vbb-stations-cli#3]
I just installed v0.5.0 and noticed that you've added the operating lines to the pretty output. Great!

Any plans to add these to the csv-format output as well? (Would like to include the operating lines in my VBBar script; otherwise it's ready for upload.)

**Comment by derhuerst** [comment]
Will do, give me a few minutes! 😀

**Comment by derhuerst** [comment]
Using CSV output, I can only give you string of comma-separated line ids, because the line names may be ambiguous. So you would have to manually look them up.

**Comment by derhuerst** [comment]
`vbb-stations-cli@0.6.0` should have this now. The output looks like the following:

```
id,name,latitude,longitude,weight,lines
9044201,U Berliner Str. (Berlin),52.487051,13.331361,26185,"104,N7,N9,N42,U7,U9"
```

**Comment by JayBrown** [comment]
That's a-ok. All I need is `tr , ' '` for the echo command to "prettify" it… and if I need to awk through each line, the comma-delimiter would come in handy as well. Thank you.

**Comment by derhuerst** [comment]
> Using CSV output, I can only give you string of comma-separated line ids, because the line names may be ambiguous.

Sorry, i forgot what I mentioned above, will change it to ids.
