### ISSUE TITLE
Invisible coordinates in pretty mode (iTerm, zsh, zprezto)

### ISSUE THREAD

**Issue by JayBrown** [derhuerst/vbb-stations-cli#4]
I just noticed that the coordinates are not shown in my shell:
http://i.imgur.com/FtynutH.png

They appear only when I select the line(s):
http://i.imgur.com/e3huBnA.png

This is not a problem with OS X standard "Terminal" app using bash.
http://i.imgur.com/GyxdXE6.png

The problem occurs in iTerm (latest version), using the zsh with zprezto. (Also occurs, when I switch to bash in iTerm.)

Weird. :)

**Comment by derhuerst** [comment]
I noticed there's two kinds of themes. One is applied by your shell/shell framework. fish, for example, seems to translate colors before sending them out. Also, terminal emulators (like iTerm) have themes which transform colors.

Will try to debug this, but I'm pretty sure, it's iTerms fault. 😁

**Comment by derhuerst** [comment]
`vbb-stations-cli` just [calls `chalk.gray` to print the coords](https://github.com/derhuerst/vbb-stations-cli/blob/79e18d9/formats.js#L38-L40).
